### ISSUE TITLE
#endif incorrectly closes comments.

### ISSUE THREAD

**Issue by matter123** [jeff-hykin/cpp-textmate-grammar#359]
Comments are replaced with whitespace in phase 3 of translation. The preprocessor is executed in phase 4 of translation. Therefore with regards to preprocessor conditionals, comments that contain preprocessor instructions should be ignored.

This likely affects raw-string literals as well, but I am going to file a separate issue with that after investigating the phase 1 & 2 rewindings in raw string literals.

Example
```cpp
#if 1
// the below comment completely consumes the #if 0/#endif
/* a comment
#if 0
this is still a comment
#endif
still a comment
*/ // should not be marked as invalid
#endif
```

Example Image:
<img width="544" alt="Screen Shot 2019-08-19 at 09 10 23" src="https://user-images.githubusercontent.com/714007/63281311-42369380-c261-11e9-8cdf-49052ae2232f.png">

From: https://github.com/microsoft/vscode-cpptools/issues/4104#issuecomment-522416336

**Comment by matter123** [comment]
Only `#endif` causes an error with raw string literals, So I'll just piggyback on this issue.

```cpp
#if 1
R"(
/* not a comment
#endif
)"
*/ // this is an illegal terminator
```

<img width="352" alt="Screen Shot 2019-08-19 at 09 26 34" src="https://user-images.githubusercontent.com/714007/63282350-79a63f80-c263-11e9-9d30-a4332e915504.png">

**Comment by matter123** [comment]
This will be hard to fix without code duplication due to no way of allowing comments and raw string literals to overshoot the while pattern.

One potential solution is that the while pattern ends when a comment/raw string starts, and when that ends it picks back up, that requires some chaining of begin/end patterns, however.

Something like (hope this is clear)
```
conditional_context:
 start_pattern: # the ifdef pattern
 end_pattern: lookAheadFor(/./) # end this range the moment sub patterns do not consume a character
 includes:
  left_side:
   start_pattern /\G/,
   while_pattern: # endif or lookAhead For (raw string or block comment)
  comment: #normal comment
  raw_string: # normal raw string
  right_side:
   start_pattern: LookBehindFor(comment end or raw string end)
   while_pattern: # endif or lookAhead For (raw string or block comment)
  white_space: # consumes whitespace to prevent premature closure of outer pattern
   match: /\s++/
```
