### ISSUE TITLE
Incorrect highlighting of override and final C++ modifiers if both are used

### ISSUE THREAD

**Issue by r44083** [jeff-hykin/cpp-textmate-grammar#511]
Checklist

- [x] This problem exists even with the setting `"C_Cpp.enhancedColorization": "Disabled"`
- [ ] This bug exists for C
- [x] This bug exists for C++
- [ ] This bug exists for Objective-C
- [ ] This bug exists for Objective-C++

## The code with a problem is:
```cpp
class B
{
    virtual void test() override final {};
};
```

## It looks like:
Only ```final``` is highlighted:
![image](https://user-images.githubusercontent.com/13915612/96506215-f108a200-125f-11eb-997a-60670e221ec6.png)

## It should look like:
Both modifiers (```override``` and ```final```) are highlighted.

**Comment by jeff-hykin** [comment]
Fixed (as of just now) install the extension to apply the fix immediately 👍

**Comment by j-cortial** [comment]
When several qualifiers are present after the function signature, the associated scopes are not properly computed.
For instance, for the above example:
```
- source: override
  scopesBegin:
    - storage.modifier.specifier.functional.post-parameters.override
    - final
- source: final
  scopesEnd:
    - storage.modifier.specifier.functional.post-parameters.override
    - final
```
